### PR TITLE
feat: helmfile apply [--auto-approve]

### LINKED ISSUE #205: Only sync release if there is a difference
Any possibility of adding a feature to run the sync for releases in the helmfile that have differences.

With the feature of `helm diff` I would imagine this would be something that would fit?

### PR DESCRIPTION
**Pull request by mumoshu**
This command syncs releases only if there is any difference between the desired and the current state. It asks for an confirmation by default. Provide `--auto-approve` flag after the `apply` command to skip it.

Resolves #205

### CODE REVIEW

**Comment by kody-abe** [comment]
@mumoshu Probably need a README update as well? Thanks for getting this in!

**Comment by mumoshu** [comment]
@kody-abe Thanks for your review! I added some doc updates now.

**Comment by blissd** [comment]
This broke local testing deployments for us as we run `helmfile` non-interactively from scripts. I think this is a bit backwards. After all, I just ran a command to delete stuff, don't make me confirm that I really mean it.

An approach I would prefer would be to restore the original behaviour, but add a `--dry-run` flag that would simply print the commands that would execute instead of actually executing them.

**Comment by mumoshu** [comment]
@blissd See https://github.com/roboll/helmfile/issues/354#issuecomment-423220668 - you aren't forced to use `apply`!

**Pull request merged**
