### PR TITLE
Feature/diff simple

### PR DESCRIPTION
**Pull request by astorath**
Added an option to use helm-diff's `--output` flag, e.g.:
```
helmfile diff --diff-output simple
```

see: https://github.com/databus23/helm-diff/pull/221

### CODE REVIEW

**Comment by mumoshu** [comment]
@astorath Hey! Thanks for the PR. Just a quick idea- can we use just `--output` instead if it doesn't collide with any existing flag?

**Comment by astorath** [comment]
@mumoshu  Well, my guess was that in future there might be some flag to control `helmfile` output. I don't mind to replace the flag though.

**Comment by mumoshu** [comment]
@astorath Hey! Thanks for confirming. I'd guess what we might add in the future for controlling output target could be something that sounds more like `--output-dir` as helm's, because we need to deal with multiple diffs of multiple releases.
I also see `kubectl get` has `-o | --output` which is for the output format. So I believe we can safely use `--output` here.

**Comment by astorath** [comment]
@mumoshu Actually it does conflict with:

https://github.com/roboll/helmfile/blob/master/main.go#L804

**Comment by mumoshu** [comment]
@astorath Thanks! Yeah, but I thought the meaning of `helm list --output` doesn't conflict with `helm diff`'s output flag.

**Comment by astorath** [comment]
@mumoshu ok, you win...

**Review by mumoshu — APPROVED** [review]
LGTM 👍 Thank you so much for your contribution and cooperation @astorath

**Pull request merged**
