### PR TITLE
Add envvar interpolation for names and namespaces

### PR DESCRIPTION
**Pull request by danielcb**
As proposed in #86.

### CODE REVIEW

**Comment by cmeury** [comment]
Seems reasonable to me. No specific reason why those fields should not be interpolatable(?) as well. I just could not think of a good reason *for* it.

**Comment by danielcb** [comment]
Cool. Yep, as said in the issue, we would like to use it in our automated deployment chain. And since everything else is already open for templating via envvars these changes would avoid us having to add an extra layer of templating around helmfile.

Let me know if there's anything missing/wrong in the PR.

**Comment by mumoshu** [comment]
Merging this following #90. But beware that we shouldn't lose benefits of declarative nature provided helmfile.yml by making it too dynamic! And I'm still exploring about how the scope of helmfile should be.

But anyway, this doesn't affect existing users so let's go ahead and see how this works in the wild!
I appreciate it if you could share us your experiences after using this feature seriously in prod 🙏

**Comment by danielcb** [comment]
Will do. Thanks!

**Pull request merged**
