### PR TITLE
feat: Merge multiple docs inside a single helmfile.yaml

### LINKED ISSUE #254: feat: Merge multiple docs inside a single helmfile.yaml
Extracted from https://github.com/roboll/helmfile/issues/59#issuecomment-416608106

This feature would allow us to template your `helmfile.yaml` according to environment values #253.

An example helmfile.yaml would look like this. Notice the document separator `---` in the middle of the yaml file:

```yaml
environments:
  default:
    values:
    - environments/default.yaml
---
respositories:
- name: your-private-git-repo-hosted-charts
  url: https://{{ .Environment.Values.githubToken }}@raw.githubusercontent.com/kmzfs/helm-repo-in-github/master/

releases:
- name: myapp
  # snip
```

#253 alone doesn't allow you to template your `helmfile.yaml` according to the environment values due to the chicken-and-egg problem. That is, helmfile.yaml needs to be templated before parsed as yaml. But templating the helmfile.yaml referencing `{{ .Environment.Values }}` requires you to load `environments:` form yaml.

This also helps the use-case of implementing ["base" and "layer" helmfiles](https://github.com/roboll/helmfile/issues/240#issuecomment-416886474).

### PR DESCRIPTION
**Pull request by mumoshu**
One caveat is that it doesn't merge arrays, but rather the latter overwrites the former.

Resolves #254

### CODE REVIEW

**Comment by luisdavim** [comment]
`imdario/mergo` has options to merge arrays aren't you using that?

**Comment by mumoshu** [comment]
@luisdavim Hey! Actually we're using mergo elsewhere in the helmfile codebase. But AFAICS, `yaml.Unmarshal` merges consumed yaml docs into the targeted desired state in the same way as `mergo`. So, I had no specific reason to use merge here.

I'd appreciate it if could inform me any specific benefit of mergo for this use, if any. Thanks!

**Comment by luisdavim** [comment]
The benefit would be that you can control wither the arrays are merged, appended or overwritten. I think that the current implementation is fine as long as it's clear to the user that the arrays are overwritten, if there's a need to change that mergo could be the solution.

**Comment by mumoshu** [comment]
@luisdavim Makes sense! But you say that mergo supports various strategies to merge arrays? All I know is `merge.WithOverride` which seems to merge arrays by replacing the one in dst with the one in src(=override).

**Comment by mumoshu** [comment]
Also, I'm not sure how everyone wants to merge arrays. Do you need appends, overrides, or both?

**Pull request merged**
