### PR TITLE
Accept chart in a local path

### PR DESCRIPTION
**Pull request by robsonpeixoto**
If the chart is in directory, for example, `./my/chart` the `helmfile -f my.yaml sync` will fail.

This PR will check if the chart starts with `./` or `../` and will transform it in a full path of the chart directory.

### CODE REVIEW

**Comment by roboll** [comment]
This seems sane. @robsonpeixoto Have you tested this? I don't have a kube environment handy right now.

**Comment by robsonpeixoto** [comment]
Yes. I'm already using in production

**Comment by roboll** [comment]
Great, thanks for the PR!

**Comment by robsonpeixoto** [comment]
Thanks @roboll

**Comment by AMeng** [comment]
@robsonpeixoto could you please create a new release with this feature?

**Comment by roboll** [comment]
Sure, just pushed `v0.5`.

**Pull request merged**
