### PR TITLE
Add go-getter support to load base helmfiles

### LINKED ISSUE #1193: Add support for referencing base helmfiles from a URL
# Use Case
If you have multiple repositories with their own helmfiles being deployed it would be helpful to syncronise certain aspects, for example the `environments` section. This would make management of the per-repository helmfiles much simpler.

# Example

## Repository helmfile.yaml

```yaml
helmfiles:
  - "./010/helmfile.yaml"
  - "./020/helmfile.yaml"
bases:
  - git+ssh://git@github.com/zoonage/helm-lib@bases/environment.yaml
```

## Library bases/environment.yaml

```yaml
environments:
  local:
    values:
      - local.yaml
  testing:
    values:
      - testing.yaml
  staging:    
    values:
      - staging.yaml
  production:
    values:
      - production.yaml
```

### PR DESCRIPTION
**Pull request by jonasrutishauser**
Resolves #1193

### CODE REVIEW

**Comment by mumoshu** [comment]
Hi! This looks good. Just confirming, but how did you test this? Is this tested to work both with or without the use of go-getter style url in a bases entry?

**Comment by mumoshu** [comment]
@jonasrutishauser Hi! This looks good. Just confirming, but how did you test this? Is this tested to work both with or without the use of go-getter style url in a bases entry?

**Comment by jonasrutishauser** [comment]
I tested it manually (simple Helmfile) with and without go-getter style url in bases.
I even tested my tests by running them against the code without my changes.

**Review by mumoshu — APPROVED** [review]
I see! Let's go ahead. Thanks for your contribution @jonasrutishauser ☺️

**Comment by mumoshu** [comment]
@jonasrutishauser Ah, would you mind adding some documentation about this feature under https://github.com/roboll/helmfile/blob/master/docs/writing-helmfile.md#layering-state-files so that it's more discoverable? Thanks!

**Pull request merged**
