### PR TITLE
Docs automation using Material for Mkdocs

### LINKED ISSUE #1755: Publish documentation
I want to propose publishing versioned docs of helmfiles. A solution such as:
* Github Pages released from a 
* mkdocs
* versioned by released tag (with `latest` pointing to the most recent tag)
* deploys automatically on every tag release

would be a great starting place.

Would there be any other requirements out of the box? Otherwise, I can start working on a PR for the implementation

### PR DESCRIPTION
**Pull request by renehernandez**
## Description

Fix #1755 

This introduces to jobs:
- A deployment of the docs on master (deployed as `vNext`), which will point to the unreleased version of the docs at https://roboll.github.io/helmfile/vNext
- A deployment of the docs on a tag, which will deploy a new version accessible at https://roboll.github.io/helmfile/$TAG

## Instructions

- Need to replace the ssh key fingerprint with the fingerprint of a new SSH in the `add_ssh_keys` section of the `deploy_docs` jobs added as a deploy key (with write permissions). Check this [post](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/) for more details
- Once we have a new tagged version of the docs, there is a one-off task that we need to perform:
```shell
mike set-default --push latest
```
This will handle the redirect so that people going to the root of the documentation, e.g. https://roboll.github.io/helmfile are redirected to https://roboll.github.io/helmfile/v0.140.0.

## New Dependencies for docs

- [mkdocs](https://github.com/mkdocs/mkdocs): Documentation framework
- [Material for mkdocs](https://github.com/squidfunk/mkdocs-material): Documentation theme
- [mike](https://github.com/jimporter/mike): For the versioning of the documentation

### CODE REVIEW

**Comment by renehernandez** [comment]
@mumoshu Let me know when you have time for reviewing this? I cannot configure the ssh key in the repo since I don't have access to the deploy keys

**Comment by renehernandez** [comment]
@mumoshu Any updates on this?

**Comment by mumoshu** [comment]
@renehernandez Hey! Well, honestly speaking I'm not yet sure how we could proceed. I don't even have administrative privilege on this repository so I can't even set up a deploy key for you. See #1824 

Shall we just merge this once I successfully confirmed this to work on my own helmfile fork?

**Comment by renehernandez** [comment]
@mumoshu Yeah, it is hard in this scenario. I think moving along the lines of https://github.com/roboll/helmfile/issues/1824, would help to reduce this friction in the future.

> Shall we just merge this once I successfully confirmed this to work on my own helmfile fork?

Without a deploy key is going to fail though, I am more inclined to hold on into this and look into transfer this project to the helmfile organization

**Comment by renehernandez** [comment]
@mumoshu Alternatively, we can implement the docs process using Github Actions, and that would use the job token automatically with the correct permission and it wouldn't require a PAT. Let me know if you want me to go down that road or prefer to wait

**Comment by mumoshu** [comment]
@renehernandez I'm more familiar with Actions so I definitely prefer using it! Note that we still need to ask @roboll to enable gh pages on this repo, though.

**Comment by mumoshu** [comment]
@renehernandez I was able to port a part of your work to the mkdocs + ReadTheDocs config used in the new helmfile repo https://github.com/helmfile/helmfile/commit/3267484f47eda98973e9b85098d8b490fcace728 and it's working like a charm 🎉 

https://helmfile.readthedocs.io/en/latest/

I'm awaiting your response at https://github.com/roboll/helmfile/issues/1824#issuecomment-1086770394 so it would be great if you could see it when you have some time.

Thanks again for your contribution!

**Pull request closed without merging**
