### PR TITLE
bump to go 1.17.3 with alpine 3.13

### PR DESCRIPTION
**Pull request by itscaro**

### CODE REVIEW

**Comment by mumoshu** [comment]
Oh well what's going on with the image build? 🤔 

```
make: /bin/sh: Operation not permitted
make: git: Operation not permitted
make: /bin/sh: Operation not permitted
```

**Comment by mumoshu** [comment]
I guess there should be some go.mod/sum changes like we've seen in #1951

**Comment by itscaro** [comment]
> I guess there should be some go.mod/sum changes like we've seen in #1951

Since we update Go version, go.mod is not required to be updated, I voluntarily did this to avoid updating dependencies along with the Go version bump. If you prefer, we could do it in the same PR :-)

> Oh well what's going on with the image build? 🤔

Something is not right with Circle CI, locally the build passes :(

**Comment by itscaro** [comment]
@mumoshu All green ✅

**Review by mumoshu — APPROVED** [review]
LGTM! Thanks for your contribution ☺️

**Pull request merged**
