### PR TITLE
fix: spec.KubeContext does not fallback to HelmDefaults.KubeContext

### PR DESCRIPTION
**Pull request by katsew**
fixes: #1782

### CODE REVIEW

**Comment by katsew** [comment]
Hi, @mumoshu 

I made a fix of the issue that I opened yesterday,
but I'm not sure this fix works with no side effect.
Let me know if you have any concerns, thanks.

**Comment by katsew** [comment]
I have tested the fix by running `make test`, then I fixed the failed tests,
but I'm not adding any tests for this fix.
Where should I put the test of this fix if it's necessary?

**Comment by mumoshu** [comment]
@katsew Hey! Thanks for the PR. This looks great so far.

I'm still figuring that out, but could you start by adding a single test case "without the default kubecontext", in `pkg/app/app_apply_test.go`? That would help us clarifying what are differences when you've specified kubecontext or not, and also help us to not introduce any regression on cases that we don't set the default kubecontext.

**Comment by katsew** [comment]
Hi, @mumoshu . Thanks for the response.
I'll add a test for the case you provided.

**Comment by katsew** [comment]
@mumoshu 

I copy-n-pasted existing test cases which depend on the constants `helmV2ListFlags` and `helmV3ListFlags` ,
then I added new constants `helmV2ListFlagsWithoutKubeContext`, `helmV3ListFlagsWithoutKubeContext` to test the fix.
If it's ok, then I'll squash the commit.

Please review it, thanks.

**Comment by mumoshu** [comment]
@katsew Thank you so much for your effort! Everything looks great. Let me squash it and merge this.

**Review by mumoshu — APPROVED** [review]

**Pull request merged**
