### PR TITLE
feat: `helmfile diff` also works against non-existent releases

### LINKED ISSUE #127: Helmfile diff upgrade does not work
I have tried getting this to work with zero success.
With this helm file:
```
repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com

releases:
  - name: test-site
    chart: stable/wordpress
    version: 1.0.0
    set:
      - name: mariadb.persistence.enabled
        value: false
      - name: ingress.enabled
        value: true
      - name: ingress.hostname
        value: test.example.com
      - name: ingress.annotations.kubernetes\.io/ingress\.class
        value: nginx
      - name: persistence.enabled
        value: false

```
I get this output.
```
09:36 $ helmfile --file ./HelmfileTest.yaml diff upgrade
exec: helm diff test-site stable/wordpress --version 1.0.0 --set mariadb.persistence.enabled=false,ingress.enabled=true,ingress.hostname=test.example.com,ingress.annotations.kubernetes\.io/ingress\.class=nginx,persistence.enabled=false
Command "helm diff" is deprecated, use "helm diff upgrade" instead
Error: chart "wordpress" matching 1.0.0 not found in stable index. (try 'helm repo update'). No chart version found for wordpress-1.0.0
Usage:
  diff [flags]
  diff [command]

Available Commands:
  revision    Shows diff between revision's manifests
  rollback    Show a diff explaining what a helm rollback could perform
  upgrade     Show a diff explaining what a helm upgrade would change.
  version     Show version of the helm diff plugin

Flags:
  -h, --help                   help for diff
      --no-color               remove colors from the output
      --reset-values           reset the values to the ones built into the chart and merge in any new values
      --reuse-values           reuse the last release's values and merge in any new values
      --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray   allows suppression of the values listed in the diff output
  -q, --suppress-secrets       suppress secrets in the output
  -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
      --version string         specify the exact chart version to use. If this is not specified, the latest version is used

Additional help topics:
  diff

Use "diff [command] --help" for more information about a command.

Error: plugin "diff" exited with error
err: exit status 1
```

From the looks of it the helmfile binary is not passing the upgrade option into the helm diff command.

### PR DESCRIPTION
**Pull request by mumoshu**
Resolves #127

### CODE REVIEW

**Comment by cmeury** [comment]
Tested this locally, works fine:

```
$ helmfile  diff
exec: helm diff upgrade --allow-unreleased httpbin charts/httpbin --kube-context minikube
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
..
```

But I had to explicitly install helm-diff 2.9.0+2. We need to make sure to add a release note, possibly also specifying the [workaround for the failing update](https://github.com/databus23/helm-diff/issues/59).

**Comment by sstarcher** [comment]
I'm also running into this issue with `2.9.0+2` - https://github.com/databus23/helm-diff/issues/58

**Comment by sstarcher** [comment]
And by that I mean I'm running into that issue on any reinstall of the plugin if I specify a version.

**Comment by sstarcher** [comment]
Can we get this merged?

**Comment by mumoshu** [comment]
@cmeury Thanks! I'll include it in the release note.

**Pull request merged**
