### PR TITLE
Bump golang to v1.14.2

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by renehernandez** [comment]
@mumoshu  I could opened another PR to tackle upgrading to golang 1.14 if this one does not have traction anymore.

That issue delayed me yesterday while I was setting up helmfile on my local machine, cause I have go 1.14 and had to install 1.13 to do the other contribution

**Comment by chenrui333** [comment]
@renehernandez sorry for the delay, let me pick up on this PR again.

**Comment by renehernandez** [comment]
@chenrui333 I think you need to rebase master onto your branch. There are conflicts in the PR

**Comment by chenrui333** [comment]
yeah, I just did (PR is quite behind :) )

**Comment by renehernandez** [comment]
> yeah, I just did (PR is quite behind :) )

Gotcha, great!!

**Comment by chenrui333** [comment]
```
could not deduce `environment:` block, configuring only .Environment.Name. error: failed to read helmfile.yaml.part.0: environment values file matching "env.*.yaml" does not exist in "."
error in first-pass rendering: result of "helmfile.yaml.part.0":
```

**Comment by mumoshu** [comment]
I think they aren't actually failures but logged error messages.

The actual failures seem to be coming from possible changes in TableWriter. Probably it changed how the empty table column is filled with spaces:

image

**Comment by chenrui333** [comment]
I see, let me revert those space trim stuff.

**Comment by chenrui333** [comment]
@mumoshu good to go. 🚀

**Pull request merged**
