### PR TITLE
feat: Release Template

### LINKED ISSUE #428: Prescriptive directory structure for "magic" values files
I've written a helmfile containing abut 40 releases and I'm having to repeat myself _a lot_:

Example:
```
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
    version: 0.3.2
    values:
      - "./values/logging/heapster/common.yaml"
      - "./values/logging/heapster/{{ .Environment.Name }}.yaml"
    secrets:
      - "./values/logging/heapster/common-secrets.yaml"
      - "./values/logging/heapster/{{ .Environment.Name }}-secrets.yaml"

  - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard
    version: 0.10.0
    values:
      - "./values/kube-system/kubernetes-dashboard/common.yaml"
      - "./values/kube-system/kubernetes-dashboard/{{ .Environment.Name }}.yaml"
    values:
      - "./values/kube-system/kubernetes-dashboard/common-secrets.yaml"
      - "./values/kube-system/kubernetes-dashboard/{{ .Environment.Name }}-secrets.yaml"
```

One feature I really like about Ansible is that it automatically looks for it's values files for each "playbook" in [a certain directory structure](https://docs.ansible.com/ansible/latest/user_guide/playbooks_best_practices.html#directory-layout), and looks in multiple locations in a known order, allowing easy environment specific overrides, etc.

I think it would be really nice if `helmfile` automatically looked for a `values/<namespace>/<release-name>` directory and then automatically loaded (in order):
 1. A common file regardless of environment _(maybe `values.yaml` or `common.yaml`)_.
 2. An environment specific file (e.g `production.yaml`).
 3. Any files explicitly listed in the `helmfile.yaml` _(in order)_.

And then a similar process for secrets (either in a `secrets/<namespace>/<release-name>` directory or in `values/<namespace>/<release-name>`, with files suffixed with `-secrets` treated as secrets e.g `production-secrets.yaml`.)

Another things is that if helmfile can't stat the file, it errors out (which is great in that it stops mistakes from missing files), but it would be nice if a a switch could be set so that a certain file and/or directory not existing is a warning, not an error.

**Example Directory Tree:**
```
values/
    kube-system/                      # 'kube-system' namespace
        dashboard/                    # 'dashboard' release
            production.yaml           #  production Environment specific values
            production-secrets.yaml   #  production Environment specific secrets
            staging.yaml              #  staging Environment specific values
            values.yaml               #  contains values common to all Environments
        heapster/
            values.yaml               #  only common values.yaml is provided, no environment specific values are needed.
    web/                              # 'web' namespace
        [..]                          # sub-directories similar to above
```

Then my `helmfile.yaml` could be simplified to:

```
  - name: heapster
    namespace: kube-system
    chart: stable/heapster
    version: 0.3.2

  - name: kubernetes-dashboard
    namespace: kube-system
    chart: stable/kubernetes-dashboard
    version: 0.10.0
```

### PR DESCRIPTION
**Pull request by mumoshu**
This feature is supposed to help advanced use-cases like Conventional Directory Structure explained in several issues like #428.

Newly added configuration keys `templates`, `missingFileHandler`, and the ability to defer executing template expressions in `values`, `secrets`, `namespace`, and `chart` of releases allows you to abstract away repetitions into a reusable template:

```yaml
templates:
  default: &default
    missingFileHandler: Warn
    namespace: "{{`{{ .Release.Name }}`}}"
    chart: stable/{{`{{ .Release.Name }}`}}
    values:
    - config/{{`{{ .Release.Name }}`}}/values.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}.yaml
    secrets:
    - config/{{`{{ .Release.Name }}`}}/secrets.yaml
    - config/{{`{{ .Release.Name }}`}}/{{`{{ .Environment.Name }}`}}-secrets.yaml

releases:
- name: envoy
  <<: *default
- name: metricbeat
  <<: *default
# and so on..
```

See the updated documentation for more details.

Resolves #428

### CODE REVIEW

**Comment by mumoshu** [comment]
Thanks! Let's see how this works in the wild.

**Comment by sstarcher** [comment]
Thanks, I'll check this out.

**Comment by sstarcher** [comment]
Just tested it out it's working great, but I do now get 50 messages of "skippping blah" per run.
One of my helmfile went from 175 lines to 125 lines.  A pretty solid reduction.

**Comment by sstarcher** [comment]
The repositories, templates, and environments block now takes about about 1/3rd of my file weighting in at 45 lines that is essentially duplicated between half a dozen helmfiles.

**Comment by mumoshu** [comment]
Glad it worked 👍 

Regarding the "skipping blah" logs, perhaps you'd need a better log-level for it, something other than `Warn` or `Error` - Would it be `Debug` so that helmfile won't print it at the default log-level of `Info`?

**Comment by mumoshu** [comment]
> The repositories, templates, and environments block now takes about about 1/3rd of my file weighting in at 45 lines that is essentially duplicated between half a dozen helmfiles.

Nice. Then we need "includes" for that, right? :) #380

**Comment by mumoshu** [comment]
And probably use a "global variable"(#398) across the helmfiles to locate the "library" helmfile that should be included to all of em.

**Comment by sstarcher** [comment]
@mumoshu ya, something like debug would work great is that already support?  I glanced at the code and it was not immediately apparent.

**Comment by mumoshu** [comment]
It isn't supported yet, but should't be that hard to add. I'll do it later.

In the meantime, more feedbacks/idea on how to shape global vars and
includes or whatever works are appreciated.

I'm eager to reduce your repetitions!
2019年1月22日(火) 3:08 Shane Starcher <notifications@github.com>:

**Comment by sstarcher** [comment]
@mumoshu excellent thanks I'll think more about the globals.

**Comment by georgevella** [comment]
Sorry to bring this PR back to life, but got a question about this feature.  Any particular reason why the `version` field is not templated the same way as `chart`, `namespace`, etc. ?

**Comment by sstarcher** [comment]
several fields are not templated such as labels, but that feature could be added.

**Comment by mumoshu** [comment]
@georgevella Would you mind creating an issue to track that? Thanks!

**Comment by mumoshu** [comment]
Just for reference, templating for labels is tracked in #446

**Pull request merged**
