### PR TITLE
Add basic repository authentication

### PR DESCRIPTION
**Pull request by InTheCloudDan**
We have a remote repository that requires username and password to authenticate to. This PR enables that basic functionality.

### CODE REVIEW

**Comment by InTheCloudDan** [comment]
One thing I did notice is that with the way I handled it, even if it's an environment variable it prints out the value to screen as part of the helm exec. I'm not sure if it'd be worth hiding the password somehow.

**Comment by mumoshu** [comment]
Hi, thank you so much for this!

The proposed feature and code LGTM, but yes, we should passwords somehow.
Otherwise one needs to hide it by piping a helmfile run to `sed` to mask passwords? 😃 

You can browse #93 and 79 for more context. I'm considering to introduce log levels. How about `helm repo add` is logged only when the log level is greater than or equal to `DEBUG`?

**Comment by InTheCloudDan** [comment]
That would work for me, possibly log "Adding Repositories" as a generic message to know what stage the exec is at.

If that's going to be handled outside of this PR, would you like me to update the README with a temporary warning so this can be merged in, then the warning could be removed when the final decision is made/implemented?

**Comment by mumoshu** [comment]
@InTheCloudDan Thanks again! The generic message would be a great idea.

A warning in README would also be nice. I'll merge this asap after you added an additional commit for that 👍

**Comment by InTheCloudDan** [comment]
Added a basic warning. I didn't want to go to overboard with it and figured makes sense next to info about the helm version. If there's any changes you want please let me know.

**Pull request merged**
