### PR TITLE
doc: Update documentation about layering release values

### PR DESCRIPTION
**Pull request by a-hat**
`setTemplate` and `valuesTemplate` do not work, I think it is correct without the `Template` suffix.

I also added a note to the documentation regarding this issue https://github.com/roboll/helmfile/issues/836

### CODE REVIEW

**Comment by mumoshu** [comment]
@a-hat Hey! Thanks for your support.

This part of the documentation specifically explain how `Release Templating` works. Are you sure you've tested it with the `Release Template` feature, or just regular values without nested template expressions in it?

**Comment by mumoshu** [comment]
The point is that this shouldn't work:

```
    setTemplate:
    - name: '{{`{{ .Release.Name }}`}}'
      values: '{{`{{ .Release.Namespace }}`}}'
```

As until #823 nested template expressions that are starting with:

```
{{`
```

and ending with:

```
`}}
```

are rendered as-is without template expressions being evaluated.

**Comment by a-hat** [comment]
Hi @mumoshu!

After reading the documentation I tried something like this (note the `valuesTemplate` in the `templates` map) to set values in a release template:

```
templates:
  default: &default
    valuesTemplate:
    - image: default    

releases:
- name: demo
  <<: *default
  chart: stable/traefik
  version: ^1.70.2
  values:
  - image: demo
```

which gives me these errors:

```
in ./helmfile.yaml: failed to read helmfile.yaml: reading document at index 1: yaml: unmarshal errors:
  line 3: field valuesTemplate not found in type state.TemplateSpec
  line 3: field valuesTemplate not found in type state.ReleaseSpec
```

 Is the documentation referring to something else which I am missing?

**Comment by mumoshu** [comment]
@a-hat `valuesTemplate` should be available since helmfile v0.82.0! Which version of helmfile are you using?

Btw, in your example you don't need `valuesTemplate`. Just use `values`.

```
templates:
  default: &default
    values:
    - image: default    

releases:
- name: demo
  <<: *default
  chart: stable/traefik
  version: ^1.70.2
  values:
  - image: demo
```

**Comment by a-hat** [comment]
I see, thanks for the clarification. I was using version 0.81.3, so this is why `valuesTemplate` did not work.

I updated the PR and left the section about layering `values`. Does this make sense for you?

**Comment by mumoshu** [comment]
@a-hat Thanks!

Would you mind prepend `## Layering Release Values` to the sentences you've just added?

The sentences are correct. I believe it should reside within a dedicated section though.

**Comment by a-hat** [comment]
Thanks for your feedback! Makes sense, I have updated the doc.

**Pull request merged**
