### PR TITLE
feat: Add `needs: [NS/NAME]` for controlling installation/deletion order declaratively

### LINKED ISSUE #715: feat: "dependsOn" for release dependencies
I know Helmfile can already do release dependencies by ordering releases manually via naming conventions for helmfiles or limiting concurrency.

Ability to explicitly declare dependencies would be a major step towards making Helmfile more *declarative*. 

My initial idea was to base it on release names like so:

```yaml
releases:

- name: prometheus
  dependsOn: ["nginx-ingress"]
  chart: stable/prometheus
  values: []

- name: nginx-ingress
  chart: stable/nginx-ingress
  values: []
```

It would be even nicer to base it on release labels:

```yaml
releases:

- name: prometheus
  dependsOn:
    group: core
  namespace: prometheus
  chart: stable/prometheus
  values: []

- name: nginx-ingress
  labels:
    group: core
  chart: stable/nginx-ingress
  values: []
```

### PR DESCRIPTION
**Pull request by mumoshu**
Introduces DAG-aware installation/deletion ordering to Helmfile.

`needs` controls the order of the installation/deletion of the release:

```yaml
relesaes:
- name: somerelease
  needs:
  - [TILLER_NAMESPACE/][NAMESPACE/]anotherelease
```

All the releases listed under `needs` are installed before(or deleted after) the release itself.

For the following example, `helmfile [sync|apply]` installs releases in this order:

1. logging
2. servicemesh
3. myapp1 and myapp2

```yaml
  - name: myapp1
    chart: charts/myapp
    needs:
    - servicemesh
    - logging
  - name: myapp2
    chart: charts/myapp
    needs:
    - servicemesh
    - logging
  - name: servicemesh
    chart: charts/istio
    needs:
    - logging
  - name: logging
    chart: charts/fluentd
```

Note that all the releases in a same group is installed concurrently. That is, myapp1 and myapp2 are installed concurrently.

On `helmdile [delete|destroy]`, deleations happen in the reverse order.

That is, `myapp1` and `myapp2` are deleted first, then `servicemesh`, and finally `logging`.

Resolves #715

### CODE REVIEW

**Comment by RobertoUa** [comment]
what about upgrades? If releases A & B are already installed and then I try to upgrade both charts (helmfile apply) where chart A has added a resource & chart B requires that new resource.

**Comment by mumoshu** [comment]
@RobertoUa Hey! An upgrade works the same as an installation. Does it work for you?

**Comment by RobertoUa** [comment]
Great! 
One more question, Can `B` depend on `A` if `A` was defined in a different helmfile?

**Comment by mumoshu** [comment]
@RobertoUa Thanks for confirming!

Regarding another question, the answer is unfortunately no.

But I'm considering to deprecate sub-helmfiles and recommend `bases`:

```yaml
bases:
- base-A.yaml

releases:
- name: B
  needs:
  - ns-a/A
```

`base-A.yaml`:

```yaml
releases:
- name: A
```

Or even in favor of the `tpl` + `readFile` pattern:

```yaml
releases:
{{ tpl (readFile "tpl-A.yaml") (dict "Values" (dict "ns" "ns-a")) }}
- name: B
  needs:
  - ns-a/A
```

`tpl-A.yaml`:

```yaml
name: A
namespace: {{ .Values.ns }}
```

**Comment by RobertoUa** [comment]
>Does it work for you?

I finnaly tried it today, and it doesn't :(
It doesn't work for already deployed releases and when I'm using `--selector`.
It says `A needs B, but it must be one of C, A` (yes, it proposes to `need` itself). But I depend on 5 different releases and they're not in the list, only 1 of them and it seems it's because release C is getting updated during `helmfile apply`

**Comment by mumoshu** [comment]
@RobertoUa Thanks for the report! Interesting.

Can I probably reproduce it by writing a helmfile.yaml like this?

```
releases:
- name: my-release
  namespace: default
  needs:
  - consul
  - elk
  - external-secrets
  - kube-system/kubernetes-externalsecrets
  - kube2iam
  - redis
  - storage
- name: consul
- name: elk
# ...
```

A minimum example for reproduction would be helpful if you have one 🙏

**Comment by RobertoUa** [comment]
Sorry, can't help you with an example file ATM. But I refactored my helmfile from using `helmfiles:` to `bases:` + `needs` (it's pretty big)

My guess is that it doesn't work if dependencies doesn't have any changes (or if `--selector` is used, which is basically the same).
I think, that in my example `kubernetes-external-secrets` was included in the list only because I updated its version (diff showed changes). Does it make sense?

**Comment by mumoshu** [comment]
@RobertoUa Ahh, good point! Yeah `--selector` should affect this due to how this feature is implemented today.

That is, currently a DAG is computed after the `--selector` is applied to filter only affected releases.
Probably we need change the DAG to be computed before filtering releases.

**Comment by jurgenweber** [comment]
This does not seem to work at all for me, using a helmfile. Maybe I am doing something wrong, I am unsure:

```
helmfiles:
  - path: helmfile/repositories.yaml
  - path: helmfile/helmdefaults.yaml.gotmpl
    values:
      - cluster/{{ env "HELMFILE_CLUSTER" | default "local" }}.yaml
  - path: helmfile/environments.yaml
  - path: helmfile/releases.yaml.gotmpl
    selectors:
      - name=ingress
    values:
  environments.NAME.values of path/to/subhelmfile.yaml
      - cluster/{{ env "HELMFILE_CLUSTER" | default "local" }}.yaml
```

now releases.yaml.gotmpl:
```
releases:

  - name: prometheus-operator
    namespace: devops
    chart: stable/prometheus-operator
    installed: {{ .Values | get "prometheus.operator.installed" true }}
    values:
      - ../charts/devops/prometheus-operator/alertmanager.yaml
      - ../charts/devops/prometheus-operator/exporters.yaml
      - ../charts/devops/prometheus-operator/grafana.yaml
      - ../charts/devops/prometheus-operator/prometheus-operator.yaml
      - ../charts/devops/prometheus-operator/prometheus.yaml

  - name: ingress
    chart: stable/nginx-ingress
    namespace: ingress
    needs:
      - devops/prometheus-operator
    installed: {{ .Values | get "ingress.installed" true }}
    values:
      - ../charts/ingress/nginx.yaml
```

so prometheus is not installing first so I keep getting a CRD error with ingress:
```
err: release "ingress" in "releases.yaml.gotmpl" failed: failed processing release ingress: helm exited with status 1:
  Error: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
  Error: plugin "diff" exited with error
```

thoughts?

**Comment by mumoshu** [comment]
@jurgenweber Hey! The bad news is that this is a long-standing issue in helm-diff that is unlikely to be fixed.

The good news is that it would work with helm 3, as we managed to fix it in 3: https://github.com/databus23/helm-diff/issues/158

Would you mind trying again with helm v3? You can run helmfile with `HELMFILE_HELM3=1` set, like `HELMFILE_HELM3=1 helmfile apply`.

Another workaround that would be useful if you need to use helm v2 is keep using sub-helmfiles. Sub-helmfiles are processed in the order of declaration(you may know) so moving the prometheus-operator to the first sub-helmfile will fix the issue.

**Comment by jurgenweber** [comment]
Oh, yeah. I knew diff wouldn't work. Sorry, I have CnP'd the wrong error. I was using 'apply' but now I am unable to replicate the issue and I have a different problem.

for now helm 3 is not an option for me.

This now is resolved (somehow) and I have a chart issue:
```
in ./helmfile.yaml: in .helmfiles[3]: in helmfile/releases.yaml.gotmpl: failed processing release prometheus-operator: helm exited with status 1:
  Error: no kind "Job" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

I must be going mad, sorry to bother you.

**Comment by mumoshu** [comment]
@jurgenweber Wow, that's happening? What's your `helm version` output?

**Comment by jurgenweber** [comment]
```
$ helm version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
```

**Comment by mumoshu** [comment]
`2.14.3` works for me anyway:

```
$ helm version
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
$ helm diff upgrade foo --allow-unreleased --set controller.admissionWebhooks.enabled=true --set controller.admissionWebhooks.patch.enabled=true nginx-ingress-1.24.7.tgz
$ helm upgrade foo --install --set controller.admissionWebhooks.enabled=true --set controller.admissionWebhooks.patch.enabled=true nginx-ingress-1.24.7.tgz
```

Maybe a helm/k8s version issue?

**Comment by jurgenweber** [comment]
yeah,; Looks like I have hit: helm/helm#6894

**Comment by mumoshu** [comment]
@jurgenweber You were faster than me! Yeah, looks like so 😢 I've reproduced it as well.

```
$ helm216 version
Client: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.0", GitCommit:"e13bc94621d4ef666270cfbe734aaabf342a49bb", GitTreeState:"clean"}

$ helm216 init --upgrade

$ helm216 diff upgrade foo --allow-unreleased --set controller.admissionWebhooks.enabled=true --set controller.admissionWebhooks.patch.enabled=true nginx-ingress-1.24.7.tgz
#works

$ helm216 upgrade foo --install --set controller.admissionWebhooks.enabled=true --set controller.admissionWebhooks.patch.enabled=true nginx-ingress-1.24.7.tgz
Release "foo" does not exist. Installing it now.
Error: no kind "Job" is registered for version "batch/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

**Comment by jurgenweber** [comment]
ok, but to my original error and problem as I can replicate it now, I am running `helmfile apply`:

```
in ./helmfile.yaml: in .helmfiles[3]: in helmfile/releases.yaml.gotmpl: failed processing release ingress: helm exited with status 1:
  Error: [unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
  Error: plugin "diff" exited with error
```

**Comment by jurgenweber** [comment]
removing diff gets me 
```
in ./helmfile.yaml: in .helmfiles[3]: in helmfile/releases.yaml.gotmpl: 2 errors:
err 0: failed processing release prometheus-operator: helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
err 1: failed processing release ingress: helm exited with status 1:
  Error: unknown command "diff" for "helm"
  Run 'helm --help' for usage.
```

**Comment by jurgenweber** [comment]
ahhhh, I get it.. When I do a `sync` the CRDs are installed but the helm chart is not since I get the 'Job' error.

I cleared the CRDs because to install again it says the CRDs are already installed.

Ok, thanks for your help. I think I am on top of it now. Might jsut rollback my helm.

**Comment by mumoshu** [comment]
@jurgenweber Glad to hear it worked!

To recap and generally speaking, for use with helm v2 the solution for ordering the crd provider and the crd user would be to use sub-helmfiles:

```
$ tail helmfile*.yaml
==> helmfile.1.yaml <==
releases:
  - name: prometheus-operator
    namespace: devops
    chart: stable/prometheus-operator

==> helmfile.2.yaml <==
    namespace: ingress
    set:
    - name: controller.admissionWebhooks.enabled
      value: true
    - name: controller.admissionWebhooks.patch.enabled
      value: true
    - name: controller.metrics.enabled
      value: true
    - name: controller.metrics.prometheusRule.enabled
      value: true

==> helmfile.yaml <==
helmfiles:
- path: helmfile.1.yaml
- path: helmfile.2.yaml
```

`helmfile diff` would still complain, but `helmfile apply` works. That's because `helmfile apply` does `diff-and-then-sync` for each sub-helmfiles one-by-one. So when helmfile is processing `helmfile.2.yaml`, it has already installed `helmfile.1.yaml` that is needed for helm 2 + helm-diff to properly show diff.

**Comment by jurgenweber** [comment]
ok, so the solution for me then is to split into two helmfiles, those that supply CRDs to others and those that require CRD's.

got it, thank you.

**Comment by mumoshu** [comment]
@jurgenweber Exactly. Happy to help 😄

**Comment by carlosmkb** [comment]
```
releases:
- name: test-1
  chart: test-1
  installed: false
  namespace: namespace-1

- name: test-2
  chart: test-2
  namespace: namespace-2
  needs: [ namespace-1/test-1 ]
```

in this case, the release `test-2` shouldn't be installed due to `installed: false` in release `test-1`.

I'm using helm `v3.0.0` and helmfile `v0.94.1`.

**Comment by mumoshu** [comment]
@carlosmkb Hey! Thanks for the feedback.

Would you mind opening a dedicated feature request for it so that I won't forget about this?

Anyways, I'd say the current behavior has its own good point.


Cosider this example:

```
releases:
- name: cluster-logging
  chart: charts/fluent-bit
  installedTemplate: {{ .Values.clusterLogging.enabled}}

- name: service-mesh
  chart: charts/istio
  needs: [ cluster-logging ]
  installedTemplate: {{ .Values.serviceMesh.enabled}}

- name: myapp
  chart: charts/myapp
  needs: [service-mesh, cluster-logging]
```

With the current behavior, `helmfile --state-values-set serviceMesh.enabled=true apply` allows you to disable the service mesh while keeping the cluster-logging running. In your proposed behavior it isn't possible.

**Comment by mumoshu** [comment]
I spotted the feature request at #1018. Thanks about that!

**Pull request merged**
