### PR TITLE
Upgrade to go v1.13.1

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by chenrui333** [comment]
Looks like some issue with `sudo -E minikube start --vm-driver=none --kubernetes-version=${K8S_VERSION}`
```
! The 'none' driver provides limited isolation and may reduce system security and reliability.
! For more information, see:
  - https://minikube.sigs.k8s.io/docs/reference/drivers/none/
* 
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"
* 
X update config: Kubeconfig does not have a record of the machine cluster
* 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by chenrui333** [comment]
Seems it is easier to just upgrade golang, and worry about the other dependencies at a different time. The minikube crash seems little bit interesting.

**Comment by jonathangiber** [comment]
Any chance this can be merged? can't make any new builds with minikube because this crash

**Comment by chenrui333** [comment]
cc @mumoshu

**Comment by chenrui333** [comment]
@mumoshu ping :)

**Comment by chenrui333** [comment]
😄 Thanks for the merge!

**Pull request merged**
