### PR TITLE
Support for azure acr helm repositories

### PR DESCRIPTION
**Pull request by javiplx**
This adds some basic support for helm repositories hosted on azure container registry (not OCI but [classic ones](https://docs.microsoft.com/en-us/cli/azure/acr/helm?view=azure-cli-latest). Add a new element to RepositorySpec to state that is externally managed and runs the az-cli command instead of the helm one.

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM! Would you mind rebasing this onto the latest commit, though?

**Comment by javiplx** [comment]
Just to solve conflict? In that case I prefer merge from upstream. Any problema with that?

**Comment by mumoshu** [comment]
@javiplx That's fine, too!

**Comment by javiplx** [comment]
Error is connection related while building image, but I have no permission to retry.

**Comment by mumoshu** [comment]
Triggered a rerun of the failed job.

**Pull request merged**
