### PR TITLE
Fix possible race while templating

### LINKED ISSUE #32: intermittent concurrent map writes - master
fatal error: concurrent map writes

goroutine 6 [running]:
runtime.throw(0x11c4712, 0x15)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:605 +0x95 fp=0xc420043908 sp=0xc4200438e8 pc=0x10292f5
runtime.mapassign_faststr(0x1194640, 0xc420078510, 0x11c2e6b, 0xe, 0x12d3980)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/hashmap_fast.go:861 +0x4da fp=0xc420043988 sp=0xc420043908 pc=0x100c5ba
text/template.(*Template).associate(0xc420056140, 0xc420056140, 0xc4200ce100, 0xe, 0x1, 0x2)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/template.go:224 +0xad fp=0xc4200439c8 sp=0xc420043988 pc=0x10ff96d
text/template.(*Template).AddParseTree(0xc420056140, 0x11c2e6b, 0xe, 0xc4200ce100, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/template.go:128 +0x11c fp=0xc420043a30 sp=0xc4200439c8 pc=0x10fe8cc
text/template.(*Template).Parse(0xc420056140, 0xc420010340, 0x34, 0x10d1eaf, 0xc420048de0, 0x2)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/template.go:205 +0x20a fp=0xc420043b40 sp=0xc420043a30 pc=0x10ff64a
github.com/roboll/helmfile/state.renderTemplateString(0xc420010340, 0x34, 0x2, 0xc420010340, 0x34, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:87 +0x45 fp=0xc420043b98 sp=0xc420043b40 pc=0x1148845
github.com/roboll/helmfile/state.flagsForChart(0xc42001a240, 0x22, 0xc420043f50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:246 +0x274 fp=0xc420043e10 sp=0xc420043b98 pc=0x11498f4
github.com/roboll/helmfile/state.(*HelmState).DiffCharts.func1(0xc420082500, 0xc42000adc0, 0x12d3218, 0x0, 0x0, 0x12a1820, 0xc420056980, 0xc4200165c0, 0xc420016410, 0xe, ...)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:171 +0x71 fp=0xc420043f10 sp=0xc420043e10 pc=0x114b371
runtime.goexit()
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc420043f18 sp=0xc420043f10 pc=0x1055841
created by github.com/roboll/helmfile/state.(*HelmState).DiffCharts
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:168 +0x1e4

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc4200165cc)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4200165c0)
	/usr/local/Cellar/go/1.9.4/libexec/src/sync/waitgroup.go:131 +0x72
github.com/roboll/helmfile/state.(*HelmState).DiffCharts(0xc420082500, 0x12a1820, 0xc420056980, 0x12d3218, 0x0, 0x0, 0x60000000008, 0x18, 0x18)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:190 +0x239
main.main.func3(0xc42009a280, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/main.go:150 +0x17f
reflect.Value.call(0x118c9c0, 0x11cc568, 0x13, 0x11c12b8, 0x4, 0xc420043778, 0x1, 0x1, 0xc4200436f8, 0x11b8e20, ...)
	/usr/local/Cellar/go/1.9.4/libexec/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x118c9c0, 0x11cc568, 0x13, 0xc420043778, 0x1, 0x1, 0xc42009a280, 0x1319988, 0x0)
	/usr/local/Cellar/go/1.9.4/libexec/src/reflect/value.go:302 +0xa4
github.com/roboll/helmfile/vendor/github.com/urfave/cli.HandleAction(0x118c9c0, 0x11cc568, 0xc42009a280, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:483 +0x180
github.com/roboll/helmfile/vendor/github.com/urfave/cli.Command.Run(0x11c133c, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11caf4b, 0x33, 0x0, ...)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/command.go:186 +0x9ed
github.com/roboll/helmfile/vendor/github.com/urfave/cli.(*App).Run(0xc420001080, 0xc42000a060, 0x2, 0x2, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/vendor/github.com/urfave/cli/app.go:237 +0x57d
main.main()
	/Users/sstarcher/go/src/github.com/roboll/helmfile/main.go:212 +0x9ea

goroutine 5 [runnable]:
text/template.(*Template).Execute(0xc420056140, 0x129f340, 0xc420100000, 0x0, 0x0, 0x0, 0x2)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/exec.go:179 +0x76
github.com/roboll/helmfile/state.renderTemplateString(0xc4200d0000, 0x39, 0x2, 0xc4200d0000, 0x39, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:93 +0xad
github.com/roboll/helmfile/state.flagsForChart(0xc42001a240, 0x22, 0xc420077f50, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:246 +0x274
github.com/roboll/helmfile/state.(*HelmState).DiffCharts.func1(0xc420082500, 0xc42000adc0, 0x12d3218, 0x0, 0x0, 0x12a1820, 0xc420056980, 0xc4200165c0, 0xc420018440, 0x13, ...)
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:171 +0x71
created by github.com/roboll/helmfile/state.(*HelmState).DiffCharts
	/Users/sstarcher/go/src/github.com/roboll/helmfile/state/state.go:168 +0x1e4

goroutine 7 [runnable]:
text/template/parse.(*lexer).emit(0xc4200ca180, 0x6)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/parse/lex.go:156 +0xc5
text/template/parse.lexText(0xc4200ca180, 0x6)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/parse/lex.go:269 +0x1e0
text/template/parse.(*lexer).run(0xc4200ca180)
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/parse/lex.go:231 +0x5f
created by text/template/parse.lex
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/parse/lex.go:224 +0x15f

goroutine 17 [runnable]:
runtime.goexit1()
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/proc.go:2365 +0x4e
runtime.goexit()
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/asm_amd64.s:2338 +0x6
created by text/template/parse.lex
	/usr/local/Cellar/go/1.9.4/libexec/src/text/template/parse/lex.go:224 +0x15f

### LINKED ISSUE #37: env interpolation sometimes randomly fails
I have a loop that runs helmfile diff 100 times.  Sometimes the following value will output true, but the majority of the time it has the correct value
```
      - name: config.s3.bucket
        value: '{{ env "S3_BUCKET" }}'
```

* exec: helm diff chart chart config.s3.bucket=true 
* exec: helm diff chart chart config.s3.bucket=bucket-name

### PR DESCRIPTION
**Pull request by mumoshu**
Fixes #32
Fixes #37

### CODE REVIEW

**Comment by mumoshu** [comment]
@sstarcher This is the only possible fix as per our discussion. Would you mind verifying if this fixes the races you're seeing?

**Comment by sstarcher** [comment]
Tested your PR and ran it 200 times with no issue.  Re-tested against master and it failed on the second run.

**Comment by mumoshu** [comment]
Same for me as https://github.com/roboll/helmfile/issues/32#issuecomment-368878165. Thx for your support!

Now, I'm looking forward to @roboll's review 😃

**Comment by foklepoint** [comment]
@roboll Would love to get this tested / merged if this fixes the race condition. Would really help adoption of helmfile at reddit

**Comment by mumoshu** [comment]
@foklepoint Just started supporting roboll to maintain this as a secondary maintainer :)
Merging this as @sstarcher and I have already verified that it's working/does fix the issue.

**Comment by sstarcher** [comment]
@mumoshu good to hear :) thanks

**Pull request merged**
