### PR TITLE
Do fail on a possible typo in `needs` entries

### PR DESCRIPTION
**Pull request by mumoshu**
Helmfile kindly fails with a friendly error when you made a typo in a `needs` entry, i.e. a `needs` entry to an undefined release triggers an error, instead of silently running the helmfile command with a wrong DAG.

Example Output:

```
in ./helmfile.needs.yaml: release(s) "app" depend(s) on an undefined release "infrastructure/cert-manager2".
Perhaps you made a typo in `needs` or forgot defining a release named "cert-manager2" with appropriate
`namespace` and `kubeContext`?
```

This prevents issues like #1959

### CODE REVIEW

**Comment by kuzaxak** [comment]
Related to that change:  https://github.com/roboll/helmfile/issues/2048

Should I provide an example repo to reproduce an issue?

**Comment by adecchi-2inno** [comment]
HI Users, I get this error with multiples releases in a machine where is the first time execute the helmfile command. 
When I execute the helmfile command in my machine where I previously installed the releases I do not have this error, but if someone else try to execute the helmfile command in other machine where he clone the repository they get the error.

**Comment by mumoshu** [comment]
@adecchi-2inno Hmm, isn't that due to the version difference?

**Comment by vbergbauer** [comment]
This release seems to be breaking common usage of selectors.
For example:
```bash
$ helmfile --selector=release=vault status
in ./helmfile.yaml: in .helmfiles[1]: in csi-secrets-store/helmfile.yaml: release(s) "vault/vault" depend(s) on an undefined release "kube-system/secrets-store-csi-driver". Perhaps you made a typo in "needs" or forgot defining a release named "secrets-store-csi-driver" with appropriate "namespace" and "kubeContext"?

$  helmfile --selector=release=vault template --skip-deps
in ./helmfile.yaml: in .helmfiles[1]: in csi-secrets-store/helmfile.yaml: release(s) "vault/vault" depend(s) on an undefined release "kube-system/secrets-store-csi-driver". Perhaps you made a typo in "needs" or forgot defining a release named "secrets-store-csi-driver" with appropriate "namespace" and "kubeContext"?
```

These work fine with the previous version

**Comment by wutongjoe** [comment]
> have same issue with [vbergbauer](https://github.com/vbergbauer) , was OK on 0.141 and 0.142 but failed on 0.143 and 0.144



> This release seems to be breaking common usage of selectors, when one release "needs" another. For example:
> 
> ```shell
> $ helmfile --selector=release=vault status
> in ./helmfile.yaml: in .helmfiles[1]: in csi-secrets-store/helmfile.yaml: release(s) "vault/vault" depend(s) on an undefined release "kube-system/secrets-store-csi-driver". Perhaps you made a typo in "needs" or forgot defining a release named "secrets-store-csi-driver" with appropriate "namespace" and "kubeContext"?
> 
> $  helmfile --selector=release=vault template --skip-deps
> in ./helmfile.yaml: in .helmfiles[1]: in csi-secrets-store/helmfile.yaml: release(s) "vault/vault" depend(s) on an undefined release "kube-system/secrets-store-csi-driver". Perhaps you made a typo in "needs" or forgot defining a release named "secrets-store-csi-driver" with appropriate "namespace" and "kubeContext"?
> ```
> 
> These work fine with the previous version

**Comment by mumoshu** [comment]
@vbergbauer @wutongjoe I can't say for sure because it really depends on your exact setup, but try messing with `--include-needs=[true,false]`, `--include-transitive-needs=[true,false]` depending on your requirement

**Comment by mumoshu** [comment]
And please don't be hesitant to open new issues with full details rather than commenting on an existing pull request. That makes me tracking the problem too hard!

**Pull request merged**
