### PR TITLE
allow empty pattern matching and move on

### LINKED ISSUE #778: deps fails on missing globbed files
We have a root helmfile similar to 
```
helmfiles:
- helm/account/helmfile.yaml
- helm/account/{{ .Environment.Name }}/services/*/helmfile.yaml
- helm/account/{{ .Environment.Name }}/teams/*/helmfile.yaml
```

In some environments some of the above may not exist.  This works fine with helmfile sync, diff, apply etc, but fails for helmfile deps.

```
Running helmfile from helm/account/prod
in ./helmfile.yaml: no file matching helm/account/prod/teams/*/helmfile.yaml found
```

### PR DESCRIPTION
**Pull request by sstarcher**
Fixes #778

### CODE REVIEW

**Comment by sstarcher** [comment]
@mumoshu anything I can do to help with this.  It was a regression between 0.6x and 0.8x

**Comment by mumoshu** [comment]
@sstarcher Thanks for reminding me! The only thing I'm struggling is about why this affects  `deps` only. I thought `ExpandedHelmfiles` in concern is called from every helmfile command but I could be wrong.

**Comment by sstarcher** [comment]
It happens to all of them not just dep.

**Comment by mumoshu** [comment]
Ah okay probably I've misread your comment somewhere!

**Pull request merged**
