### PR TITLE
Helm args are missing on diff when helmfile apply is called

### PR DESCRIPTION
**Pull request by hyunysmile**
This adds helm args to helm-diff when helmfile apply is called by:
- Changing position of helm.SetExtraArgs to before Diff

### CODE REVIEW

**Comment by hyunysmile** [comment]
> Understood. Then you can do this:
> 
> ```
> helmDefaults:
>   tillerNamespace: kube-system
>   wait: true
>   timeout: 300
>   force: true
>   kubeContext: test
> 
> releases:
>   - name: kci-priorityclass
>     chart: ../charts/kci-priorityclass
>     devel: true
>     values:
>       - ../general/kci-priorityclass/values.yaml
>       
>   - name: nginx-ingress-production
>     namespace: production-general
>     chart: gstable/nginx-ingress
>     version: 1.8.1
>     values:
>       - ../general/nginx-ingress/values.yaml
>       - ../general/nginx-ingress/production.yaml
> ```
> 
> Or
> 
> ```
> helmDefaults:
>   tillerNamespace: kube-system
>   wait: true
>   timeout: 300
>   force: true
>   kubeContext: test
>   devel: true
> 
> releases:
>   - name: kci-priorityclass
>     chart: ../charts/kci-priorityclass
>     values:
>       - ../general/kci-priorityclass/values.yaml
>       
>   - name: nginx-ingress-production
>     namespace: production-general
>     chart: gstable/nginx-ingress
>     version: 1.8.1
>     values:
>       - ../general/nginx-ingress/values.yaml
>       - ../general/nginx-ingress/production.yaml
> ```

Ok!
The second solution would work for us :)
So the current problem when `helmfile apply` is executed, 
it drops --devel arg will be solved?

**Comment by mumoshu** [comment]
@hyunysmile It depends. Do you still need it?

**Comment by hyunysmile** [comment]
> @hyunysmile It depends. Do you still need it? And if so, how will you use it? At least in your use-case `--devel` seems not useful at all 🤔

You mean, setting `devel: true` will solve my problem with current helmfile version? is it different with using args?

**Comment by mumoshu** [comment]
@hyunysmile 

> setting `devel: true` will solve my problem with current helmfile version?

Yes, that's what I mean!

Do still need a way to set `devel` from a helmfile command-line flag?

**Comment by hyunysmile** [comment]
> @hyunysmile
> 
> > setting `devel: true` will solve my problem with current helmfile version?
> 
> Yes, that's what I mean!
> 
> Do still need a way to set `devel` from a helmfile command-line flag?

Sorry for the late reply. With the way you suggest, it works. :)
I will close this pull request. Thank you.

**Pull request closed without merging**
